### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#1]
"Write down Use Cases for your App4Students together. Write one sentence per Use Case. Write the Use Cases in the Wiki of your Github repository."

**Comment by Kjani01** [comment]
Hi!

We have to write Use Cases until **Thursday, 25 April 2019, 11:55 PM**. WhatsApp isn't the best way for our communication, because Daniel doesn't use it. So we thought we would communicate here in our github-Issues, while we see us only once every week.

So every one of us should think about possible use cases and post them in this issue. An Example for a use case is: 
_"As a linear algebra student, i need an e-book reader that displays formulas correctly, so I can learn more easily."_

**Comment by Kjani01** [comment]
I did a little brainstorming and came up with a few more ideas:

_As a bookworm, i'd like a pleasant view on my e-book reader, so I can enjoy the book I'm reading even more. (Science context or any else)_

_As an author of technical books, I want a clean and accurate view with formatted margins and correct formulas, so it matches the view of a written book._ 

**Please note:** 
These ideas, we are writing down in this issue might be redundand, but we have to put the Use Cases into the wiki anyway. So whatever comes to mind, write it down and we can select the best ideas later, to transfer it into our wiki.

**Comment by GiorgioBullo** [comment]
As we can see from my storyboard, one idea could be:

_With my PC I always add some note next to the text, hence I'd like to see them in a e-book reader in my smartphone when I've got some spare time._

Another one:

_As architecture student, my book are full of pictures, so I would like to see them next to the text that describes them or at least with very quick links from text to picture and viceversa._

**Comment by DManstrator** [comment]
The idea behind my Storyboard:
_As a commuter, I want to use the time to read books / documents on my mobile without zooming and / or scrolling all the time._

(Might be the same idea as [the first in this comment](https://github.com/mobileappdevhm19/apps4students-team-3/issues/1#issuecomment-483598106)).

**Comment by maxiking203** [comment]
Use-Cases are transfered to the Wiki (https://github.com/mobileappdevhm19/apps4students-team-3/wiki/Use-Cases). More Use-Cases can be added on the Wiki.
