### ISSUE TITLE
Name and Tagline

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#10]
We need:
Name of your App4Students and a one sentence statement (e.g. FachschaftsFridgeViewer: Always know which beverages are available in the fridge at Fachschaft07)

**Comment by Kjani01** [comment]
Some ideas for a tagline already exist:

Giorgio came up with: **Hint-reader: all you need to read books and notes everywhere and anytime**

Simon had another idea: **the power of tex, the convenience of epub**

**Comment by wildeKaiserin** [comment]
Another idea would be: 
**HintReader - make science powerful**

**Comment by maxiking203** [comment]
I really like Simons suggestion!

**Comment by wildeKaiserin** [comment]
Maybe we could shorten Giorgio's idea into: Hint-reader: reading books everywhere and anytime

**Comment by Kjani01** [comment]
I like Sissys idea, because it's short and good to remember, but overall I like all of the ideas :D

**Comment by maxiking203** [comment]
Please vote for one of the suggestions on https://doodle.com/poll/eb7x8yz9rqym4v4p till the end of the day.

**Comment by maxiking203** [comment]
Name and tagline found!
Hint-reader: the power of tex, the convenience of epub
