### ISSUE TITLE
Create a Google slides presentation

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#11]
Create Google slide presentation to present your concept (link in your wiki)

        Your mission: Your App4Students in one sentence (name the key feature(s) in one sentence)
        Key Problems: (Use Cases) that your app addresses (use storyboards and personas to demonstrate them)
        Your Solution: Horizontal Prototype (show views and use problems/use cases to go through them)
        Your Product: Vertical Prototype and ideas of which technologies to use and how to implement your product
        Summary: Strengths and weaknesses of your concept

**Comment by DManstrator** [comment]
Link for the Google Presentation Slides: https://docs.google.com/presentation/d/1NJ_os-tECdt4zLisKniHOkdcefZZKxIoJnmoYX9uIzg

Tell me if you can't access them, you should be able though.

**Comment by Kjani01** [comment]
In my opinion we should put less text on the slides. We only have 5 Minutes to present and have to show the prototypes as well. If we want to present as many information as is on the slides, we should only put buzz words on the slides :D

**Comment by ghost** [comment]
We already have a lot of content, but we also need to show off the personas (in Key Problems) and screenshots of the prototypes, I guess?
Horizontal prototype screenshots are on branch _gh-pages_, Personas are in the [wiki](https://github.com/mobileappdevhm19/apps4students-team-3/wiki/Personas).

**Comment by DManstrator** [comment]
My plan was to rework the Feature Slides to what you have said, less text and showing the belonging Screenshots. I would do one feature (maybe as a Buzzword) and a Screenshot below per slide to show what it is about. And all the other features were we don't have a Screenshot for in a List of Buzzwords under "Upcomming Features".

I would do this now, are you still in University? Then I would come to you.

**Comment by maxiking203** [comment]
We left half an hour ago

**Comment by DManstrator** [comment]
Okay, nevermind. I'll update the presentation and tell you when I'm done (for today). Btw. great work with the Icons, they look really good on the Slides. :)

**Comment by DManstrator** [comment]
So, I'm done for today. I've inserted some Storyboards and the Screenshots of the horizontal Prototype, also cut down the features as wished and changed the order a bit.

A few points I would like to get a feedback from you:
- I would start with the personas (potential Users), then showing some Storyboards (Problems) and then say, that the MINT reader is targeting that. Is that okay for you?
- Maybe less details about ePub? It could be useful I guess but I'm not really sure if we should have that much text about it.

**Comment by Kjani01** [comment]
Looks much better, but it still seems to be a lot. We should definitely concentrate on the neccessary items and only on the key items of those. Will sill be plenty to say in five minutes 😀

**Comment by maxiking203** [comment]
I added screenshots of the vertical Prototype to the gh-pages branch (wiki/screenshots_vertikal-prototype) so they could be thrown into the presentation.

**Comment by ghost** [comment]
... and we should still think about choosing a master template with better information density. :)

**Comment by DManstrator** [comment]
I'm still on it, finalized my own presentation few minutes before, I'll try my best but I'm not that good at designed (as you might have seen from my Storyboard ^^). But I will add the screenshot of the vertical prototype at least later.

**Comment by DManstrator** [comment]
Okay, I've changed the Style of the presentation and adjusted the slides to fit it, also used two pages for the two Storyboards instead of one.

Feedback is appreciated. :D

**Comment by wildeKaiserin** [comment]
I think 17 slides are a way too much for 5min....
And on a few slides, there's also a lot of text, so I think it is impossible to be in time

**Comment by DManstrator** [comment]
I tried it myself and needed a bit less than 5 minutes (4min 50sec). It's hard for me to know what can be removed because what we currently have is what we should say at least in my opinion. We could potentially remove the optional User Features for Books to save a bit of time. What would you remove?

**Comment by GiorgioBullo** [comment]
the title of the presentation is really cool, but there should be also your name (or a team 3 tag), the date of tomorrow and if you want the department.

**Comment by GiorgioBullo** [comment]
do we want to keep the sentences with the question mark in slide 11? You could say that there are a lot of more features and that we have in mind to keep updated the project with future release.

**Comment by DManstrator** [comment]
> the title of the presentation is really cool, but there should be also your name (or a team 3 tag), the date of tomorrow and if you want the department.

Good point! I've added our Names and a transparent logo of the University (which doesn't look very great too be honest) but I didn't want to put that any more text on the Slides.

> do we want to keep the sentences with the question mark in slide 11? You could say that there are a lot of more features and that we have in mind to keep updated the project with future release.

Not quite sure yet. We can remove and still talk about them but then we could leave them there. I mean just saying "There are features where we are not sure yet" doesn't say anything in my opinion.

**Comment by Kjani01** [comment]
I think we are fine with the new master theme.
