### ISSUE TITLE
Wiki for our Horizontal Prototype (static, and link to high fidelity prototype)

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#13]

**Comment by ghost** [comment]
I'll be doing that in XCode storyboards, trying to display pretty much all frontend features from https://github.com/mobileappdevhm19/apps4students-team-3/wiki/Design-Phase

**Comment by ghost** [comment]
first draft looks feature-complete, will put screencaps on the wiki for comparison

**Comment by maxiking203** [comment]
Screenshots are in the Wiki! so this issue is completed.
