### ISSUE TITLE
Wiki for Photos of our paper prototypes

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#14]

**Comment by ghost** [comment]
I'll add screenshots from the XCode storyboards.

**Comment by ghost** [comment]
... so about those paper prototypes:
do we actually have to do these, or are they covered by the code/storyboards we already did?

**Comment by DManstrator** [comment]
As I've understand it, we don't need to make a paper prototype, a paper prototype is just another kind of horizontal Prototype so the XCode Storyboards should be enough. We can ask Prof. Socher to be 100% sure tomorrow but it should be alright.

**Comment by maxiking203** [comment]
paper prototypes were added to the wiki bei @pocketinfinity.
