### ISSUE TITLE
Wiki for Personas

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#15]

**Comment by ghost** [comment]
We'll do those together.

**Comment by wildeKaiserin** [comment]
I did a dummy page for 2 personas. Feel free to fill the points with information!

**Comment by Kjani01** [comment]
Simon, Sissy, Maxi and I wrote two basic personas for Lavinia and Ronald. Feel free to add some more details, if you can thing of anything.

**Comment by ghost** [comment]
i'll draw pictures ;)

**Comment by Kjani01** [comment]
The wiki is finished for our task.
