### ISSUE TITLE
create a horizontal prototype (use a tool like justinmind.com, figma, framer, or balsamiq)

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#16]

**Comment by ghost** [comment]
I'll be doing that in XCode storyboards, trying to display pretty much all frontend features from https://github.com/mobileappdevhm19/apps4students-team-3/wiki/Design-Phase

**Comment by maxiking203** [comment]
Horizontal prototype was created. Code is pushed to the feature/horizontal branch. Also Screenshots are found in gh.pages Branch and showen in the wiki!
