### ISSUE TITLE
create personas

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#17]

**Comment by ghost** [comment]
We'll do those together.

**Comment by wildeKaiserin** [comment]
![ronald](https://user-images.githubusercontent.com/32638965/56883921-6aa74180-6a68-11e9-9c99-97d05400a598.JPG)
![lavinia](https://user-images.githubusercontent.com/32638965/56883923-6aa74180-6a68-11e9-9f7c-7698d76a5bfc.JPG)

**Comment by Kjani01** [comment]
I guess we're finished with this task.
