### ISSUE TITLE
Create icon for hint reader

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#21]

**Comment by wildeKaiserin** [comment]
![logoLightbulb](https://user-images.githubusercontent.com/32638965/56847874-d7440400-68e1-11e9-8c13-6b37277f2b9b.PNG)

**Comment by wildeKaiserin** [comment]
![icon_hintreader_yellow](https://user-images.githubusercontent.com/32638965/56854151-6ed14300-6932-11e9-973f-16aecebafc76.png)

**Comment by ghost** [comment]
as requested, here's a clipping mask version of your icon ^^
![hintreader](https://user-images.githubusercontent.com/36113994/56894493-60943b80-6a86-11e9-986c-fc6244e8de71.png)

**Comment by wildeKaiserin** [comment]
Color for lightbulb:
#FF9C06

**Comment by maxiking203** [comment]
Design of the icone is also done!
