### ISSUE TITLE
What to do

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#22]
* Define what to do during Sprint 1 (set up Sprint Backlog)
*  Every team member contributes and documents contribution in Github repository (work with Github Issues or commit/push code).
* Release a first version of your app by May 24.
* Name a Team Lead.
* Name a person responsible for processes in your team (how to use Github issues, how to use your project board, how to branch, merge and use pull requests in your team).

We should discuss some of this points here and make sure we think of everything.

**Comment by GiorgioBullo** [comment]
Guys, do you think that we should parse the .hint files?

**Comment by ghost** [comment]
I'd like to avoid that. 
That format is very complex and most likely impossible to cover in the available time frame.

Also, it's the backend's job ;)

**Comment by GiorgioBullo** [comment]
so, I believe we need the code of Prof. Ruckert, otherwise I don't see how to go on

**Comment by ghost** [comment]
I'm pretty sure we were told to just assume a magical backend that can deliver whatever we need.

I am not sure if Prof. Ruckert is willing to part with he code, but we should certainly get some sort of spec from him, like, the header files - just so we know what we would be calling if the backend hooks work.

**Comment by wildeKaiserin** [comment]
Our topics are in progress or closed in other issues.
