### ISSUE TITLE
Sprint Backlog

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#23]
* Define a Sprint backlog as Github issues in your repository. 

We originally thought, we would use the Projects for our Sprint backlogs and would maybe open another Project for our implementation.
We should discuss here, how we want to do this.

**Comment by Kjani01** [comment]
* Set up a 'Project' in your Github repository. Call your project 'Sprint1'. Choose the 'Kanban (Basic) template' for your project board. 

This is basically what I explained earlier 😁

**Comment by DManstrator** [comment]
[I've created it right now](https://github.com/mobileappdevhm19/apps4students-team-3/projects/2) because I thought it was forgotten in #22. Think it can be closed.
