### ISSUE TITLE
How we are supposed to develop

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#25]
One team member sets up a basic starter app and pushes the starter app to the master branch. All other team members work on feature branches. If a feature is completed and tested, it has to be reviewed by at least one team member. The review process has to be documented in the respective Github issue. The reviewer creates a pull request to the master branch after a sucessful review.

**Comment by wildeKaiserin** [comment]
This issue is work in progress in other issues.
