### ISSUE TITLE
Backend communication

### ISSUE THREAD

**Issue by ghost** [mobileappdevhm19/HINT-Reader#26]
After some research, it seems possible to link .o files to flutter via native-build.

Would it be possibly to get pre-built libraries so we can try and link it to the flutter project?

For now, the reference cpu architecture the team has been decided on is the Snapdragon 845, because most team member have a device running on that.

Also, a header file with the public functions of the backend we can use to display the content would be appreciated.

**Comment by ghost** [comment]
Mrs. Socher, if possible, could you assign this to Mr. Ruckert?
Thanks in advance!

**Comment by wildeKaiserin** [comment]
**Spec Prio 1:**

_Method_: bool SetResolution(int height, int width) 
_Params_:
height and width = resolution of device in logical points, not pixels
_Return_: 
true if it works
_Call_:
We will always call this method, when the device resolution changes, e. g. the device rotates, the screensize changes (multitasking)

_Method_: png AskForPage(int height, int width, int startingpoint) 
_Params_:
height and width of viewport 
startingpoint:  is the ID of the element in the upper left corner to specify current page
_Return_:
image (png)
_Call_:
For now, only one call: When we open a new book, we call this method with a startingpoint of 0 to indicate the very first page of the book.

_Method_: png getNextPage()
_Return_:
image (png)
_Call_: 
whenever we change current page to following page

_Method_: png getPreviousPage()
_Return_:
image (png)
_Call_: 
whenever we change current page to previous page


**Spec Prio 2 (nice to have):**

_Method_: int getIdOfCurrentPageTopLeft()
_Returns_: 
ID of the top left element on the current page
_Call_:
We will call when we close a book to save our current position.

**Comment by ghost** [comment]
lest we forget:
png should be returned at 600dpi, we'll scale them down in the frontend. please mention in the email.

**Comment by ghost** [comment]
Additions I would like to suggest:

**PRIO 1**
_bool openFile(HINTfile f)_
* tells the backend to open a HINT file for all following operations (askForPage, getNextPage, et al.)
* will be called when opening a book in the GUI
* returns true (or int 0, because c) if file read successfully

_bool closeFile()_
* tells the backend to close the HINT file currently operating on
* will be called when closing a book in the GUI (by going back to the bookshelf view)
* returns true (or int 0) if file closed successfully

***

**PRIO 2**
_int currentPageNo()_
* returns current page number with the current resolution and viewport size
* will be used to display the current page number in the GUI ("x of ...")
* returns -1 on errors (e.g. no HINT file opened in backend, resolution not set yet ...)

_int allPageNo()_
* returns last page number with the current resolution and viewport size
* will be used to display the maximum possible page number in the GUI ("... of x")
* returns -1 on errors (e.g. no HINT file opened in backend, resolution not set yet ...)

**Comment by GiorgioBullo** [comment]
So far I would say that we have enough methods. I write here just to make a note about the screen size and resolution. I found that we could use the class MediaQueryData with which we can know both logical and physical screen size.

MediaQueryData queryData = MediaQuery.of(context);
double devicePixelRatio = queryData.devicePixelRatio;
double w =  queryData.size.width;
double h = queryData.size.height;
double w_pixel = w * devicePixelRatio;
double h_pixel = h * devicePixelRatio;

Maybe this is usefull

**Comment by ghost** [comment]
Nice find, Prof. Ruckert will be glad because that's the data he actually asked about.
So, we should change the SetResolution method call to provide physical pixels.

**Comment by Kjani01** [comment]
I think Prio 1 should be pretty good as it is now. 
But do we need a method for zooming (as Prio 2) as well? Or do we solve this only by asking a new image with different height and width?

**Comment by GiorgioBullo** [comment]
It would be too slow, I guess, to ask every time a new image

Il lun 20 mag 2019, 10:05 Kjani01 <notifications@github.com> ha scritto:

**Comment by ghost** [comment]
Prof. Ruckert's response: (comments in **bold**)

***

_bool SetResolution(int height, int width)_

 * Params: height and width = resolution of device in pixels

**probably pixel per inch (dpi) instead of pixel**

***

_png askForPage(int height, int width, int startingpoint)_
**an "unsigned int startingpoint" would be better, since the content might
be up to 4GB**

 * Params: height and width of viewport

**To go with traditional TeX,
I assume the measure of height and with is scaled points, that is
72,27pt = 1in and 1pt = (1 scaled point << 16)**

***

_png getNextPage()_

 * returns an image (png) of the following page and updates the
   internal page index
 * is called whenever we change current page to following page

**Here and in the next api call an implicit CurrentPage is assumed.
With that assumption, one could eliminate the startingpoint in the
previous api call and add  getFirstPage() to replace
askForPage( height, width, 0);
As another step, one should then probably separate page generation
and navigation. This means that get(First|Next|Previous)Page
just move the current Page, returning may be true or false;
and askForPage(height, width)**

_png getPreviousPage()_

 * returns an image (png) of the previous page and updates the internal
   page index
 * is called whenever we change current page to previous page

***

_int getIdOfCurrentPageTopLeft()_

 * returns ID of the top left element on the current page
 * We will call when we close a book to save our current position.

**I would think we use an uint64_t as return type, because for large books
the necessary information for a position alone will need an unsigned
int. And just getCurrentPage() would probably be sufficient as a name.**

***

> _int currentPageNo()_

 * returns current page number with the current resolution and viewport
   size
 * will be used to display the current page number in the GUI ("x of ...")
 * returns -1 on errors (e.g. no HINT file opened in backend,
   resolution not set yet ...)

**I would rather prefere something like unsigned int currentPosition()
giving an indication of where the current page is in the stream,and
instead of allPageNo() the have lastPosition()
firstPosition() is useless because it would always return zero.
The problem here is, that pages with lots of white space and large fonts
will require far less data than pages with a tiny font and lots of text.
So estimating the size of a page is difficult and telling how many
pages we have from the first page to current page would require
reading all the data, breaking all the paragraphs into lines, and
breaking the material into pages. That's a lot of computation.**

***

_Regarding the zoom factor, are we correct in considering changing the
resolution of the get page and scaling a resulting image in the frontend
to be equivalent to a dedicated change level zoom method?_

**Exactly, the zoom factor is something that is entirely in the front end.
The backend will just need the true size and the resolution.**

***

Very thoughtful feedback, this warrants some discussion - especially considering the model of indicating which page (at what place in the stream) we are at any given time. Thoughts?

**Comment by wildeKaiserin** [comment]
We sent an email to Prof. Ruckert. We will change the API spec in accordance to his suggestions.

**Comment by ghost** [comment]
https://github.com/mobileappdevhm19/HINT-Reader/wiki/Backend-API-Spec

**Comment by GiorgioBullo** [comment]
find dpi in java
DisplayMetrics dm = new DisplayMetrics();
getWindowManager().getDefaultDisplay().getMetrics(dm);

// these will return the actual dpi horizontally and vertically
 float xDpi = dm.xdpi;
 float yDpi = dm.ydpi;

**Comment by GiorgioBullo** [comment]
float density = (float) dm.densityDpi;       //this is what we want

**Comment by wildeKaiserin** [comment]
We sent an email to Prof. Ruckert with the link to the new repo

**Comment by wildeKaiserin** [comment]
> We sent an email to Prof. Ruckert with the link to the new repo

He answered in German, I translated it for you:

Hello,
Thank you very much. I am still waiting for Mrs. Socher's code example. Then I will try to fill the skeleton. Meanwhile, my prototype for Win32 gives the first images, so you can fill the backend in circumstances. 
Best regards, 
Martin Ruckert

**Comment by ghost** [comment]
Suggesting closing it as it's covered by https://github.com/mobileappdevhm19/HINT-Reader/issues/43
