### ISSUE TITLE
Team Lead and person responsible for processes

### ISSUE THREAD

**Issue by maxiking203** [mobileappdevhm19/HINT-Reader#30]
- Name a Team Lead.

- Name a person responsible for processes in your team (how to use Github issues, how to use your project board, how to branch, merge and use pull requests in your team).

**Comment by ghost** [comment]
Last week's discussion chose @wildeKaiserin as Team Lead crown 👑 because you pushed us to choose the project.

My humble self @pocketinfinity was selected for process responsibility. I'll try my best not to mess up the merges. Thank you for you trust.
