### ISSUE TITLE
Travis check Flutter build

### ISSUE THREAD

**Issue by maxiking203** [mobileappdevhm19/HINT-Reader#32]

**Comment by maxiking203** [comment]
I will try to do a release run to at least see that build is possible.
The apk is something for the next sprint.

**Comment by maxiking203** [comment]
Travis is building an apk know, but we don't really have access to it.
I will ask Mrs. Socher on Firday where she wants the apk.

**Comment by maxiking203** [comment]
Current version of the Travis file is in the devicesize branch.

**Comment by Kjani01** [comment]
APK is build in flutter and travis is running.
We should save the apk build somewhere.
