### ISSUE TITLE
Make BookShelfView scrollable

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#33]
The horizontal bars should be scrollable as well as the whole view.

**Comment by Kjani01** [comment]
Because of the smaller screen, I only implemented the most recent list in the horizontal BookShelfView. As soon as the View is scrollable, there should be more book suggestions to scroll through, as we see in de vertical BookShelfView.

**Comment by ghost** [comment]
Tables are not inherently scrollable, reworked into a Column of two GridViews, the main view vertical scrolling, the most recent horizontally. It's not pretty yet though - we need a divider of sorts between them. It is fully functional though (even though I don't know why it isn't loading the other image, but oh well)

screenshot WIP: [https://i.imgur.com/3YnJ6d5.png](https://i.imgur.com/3YnJ6d5.png)

**Comment by ghost** [comment]
Integrated BookCards, now ready for review.

[https://i.imgur.com/mppN0xR.png](https://i.imgur.com/mppN0xR.png)

**Comment by wildeKaiserin** [comment]
**Review**: All works, looks good. Well done! From my side, you can close the branch.

**Comment by Kjani01** [comment]
Everything works fine and is scrollable like expected.
I think we're done here and I'll close this issue. Well done!
