### ISSUE TITLE
Testing low level object linking implementation

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#34]
Testing for future backend hooks.

**Comment by maxiking203** [comment]
this is tested by implementing our sceleton. So there is way to use C in flutter or better said in Java.
Hopefully it will work as we expect.

**Comment by ghost** [comment]
We have a working prototype communicating with a c++ backend, returning a string to display in the flutter frontend.
see https://github.com/wildeKaiserin/HR_Sceleton

**Comment by maxiking203** [comment]
As there is no more feedback, i would close the issue.

**Comment by Kjani01** [comment]
While we are still waiting for feedback from Professor Ruckert, we will handle this issue in the next sprint.

**Comment by maxiking203** [comment]
A Backend using many kinds of brightes and linking also was provided by Mr. Ruckert.
So I think this is issue is also done from our side

**Comment by ghost** [comment]
I think we can close this one, given that we have actually backend hooks pretty similar to the methods we found during this research.

**Comment by maxiking203** [comment]
closed due to above mention argument(s).
