### ISSUE TITLE
Progress indicator for bookview

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#37]
Static values for now because api spec is prio 2 (we don't have necessary methods until now).

**Comment by Kjani01** [comment]
I guess we need a _Linear Progress Indicator_, like discribed here: 
https://api.flutter.dev/flutter/material/LinearProgressIndicator-class.html

**Comment by Kjani01** [comment]
Here I found a nice example of progress bars and I'm testing it on a new branch "progressBar" right now. 
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/progress_indicator_demo.dart

**Comment by Kjani01** [comment]
What I've accomplished so far: 
We have a progress bar at the top of the page in the AppBar, but I can't get rid of the Animation. We need to have a closer look at how the progress bar is designed.

**Comment by Kjani01** [comment]
Nevermind, I was just missing one _value:_ property. 
Now we need to find out, how we will calculate the current value of this bar.
And if we are fine with its place in the AppBar, or if it should be displayed somewhere else (at the bottom)

**Comment by Kjani01** [comment]
We decided that we are fine with the position of the progress bar. 
The calculation of the progress from the current page is a priority 2 function, so we will have to implement the calculation in a later sprint. 
All that is left now, is to test our progress bar.

**Comment by ghost** [comment]
Yup, looks fine.
I guess users might expect the progress bar at the bottom, but I think it looks really neat as a separator between the toolbar and the content, serving two purposes at once.
Nicely done.
