### ISSUE TITLE
Add a Privacy Policy to the App

### ISSUE THREAD

**Issue by DManstrator** [mobileappdevhm19/HINT-Reader#39]
We need a Privacy Policy for the App for Sprint 3.

**Comment by DManstrator** [comment]
I've used a Website for creating a standard Privacy Police you can find in the [Wiki](https://github.com/mobileappdevhm19/HINT-Reader/wiki/Privacy-Policy). I changed the text a bit since the Policy is for a single Person and we are a group (I -> We, my -> our, etc.).

**Comment by Kjani01** [comment]
I think the Privacy Policy is appropriate 👍 
Well done.

**Comment by maxiking203** [comment]
Are we using Firebase? because it is listed as used?
Also we should change the emailladresse o remove it completely

**Comment by DManstrator** [comment]
According to future sprints, we have to use Firebase Analytics so I already put it there so we don't have to change it later. 

And we have to provide an eMail address so I put something in we could easily find and replace it. We could use a more legit address or a real address, guess second way is better but what address should we provide then?

**Comment by maxiking203** [comment]
ok, thats a good point :D

Maybe we just create a gmail Account?

**Comment by DManstrator** [comment]
Then somebody would need to check that Account frequently which is also not good. Same for adding a personal address there.

I would ask Prof. Socher what we can do, if a fake mail address is also okay.

**Comment by DManstrator** [comment]
According to Prof. Socher, we can use the Mail Address of the Faculty (hmfk07@gmail.com) for the Policy.

Yesterday I thought our Policy was in German but as I've looked it up, it's already in English so it should be alright for now. I will contact Prof. Schuster (Holds lectures about Privacy) if she know a professional Website for Privacy Policies.

It is okay if the Policy is not ready for Sprint 2, according to the Task Description it's a goal of the final Sprint (Sprint 3).

**Comment by maxiking203** [comment]
I think for Sprint 2 thats all we can do. any other solution has to be provided by Mrs. Socher or HM, in my opinion.

**Comment by wildeKaiserin** [comment]
I'm fine with the privacy policy for now
