### ISSUE TITLE
Sceleton for backend calls

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#40]
for creating the backend functions, we need an image view with placeholder calls to set dpi and display page etc

**Comment by wildeKaiserin** [comment]
Link to repo for skeleton:
https://github.com/wildeKaiserin/HR_Sceleton

**Comment by ghost** [comment]
**SCE**ne **L**inking to **E**xternally **T**ied **O**bject **N**odes :)

**Comment by ghost** [comment]
Documentation
https://developer.android.com/studio/projects/add-native-code.html

**Comment by ghost** [comment]
@Prof. Ruckert:
Types for returns from cpp to java (and flutter via that)
https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html

**Comment by Kjani01** [comment]
NewObject is the most appropriate function to use for our Sceleton.

**Comment by Kjani01** [comment]
We might have managed to create a Sceleton, that should work in theory.  We can't test it without a functioning backend to run against. Now we will update the readme so Prof. Ruckert can understand what we did.

**Comment by ghost** [comment]
Issue on ice for now, in favour of https://github.com/mobileappdevhm19/HINT-Reader/issues/48

**Comment by maxiking203** [comment]
A Backend using many kinds of brightes and linking also was provided by Mr. Ruckert.
So I think this is issue is also done from our side
