### ISSUE TITLE
Travis deploy release

### ISSUE THREAD

**Issue by maxiking203** [mobileappdevhm19/HINT-Reader#41]
At the moment we are building the apk of our app on Travis but we don't store it somewhere.
In future it should be stored as a release for example taged with "date-branchname".

**Comment by maxiking203** [comment]
Travis is now deploying releases to GitHub. At the moment we are only doing this on the develop branch. 
We should do this on the master branch too. But the questions is, do we want the releases in the develop branch too or only in the master branch for the "real" releases?

**Comment by maxiking203** [comment]
The deployment is "implemented" with an Personal access token which I added to my profil. This token is added as an env variable to Travis.

**Comment by DManstrator** [comment]
> But the questions is, do we want the releases in the develop branch too or only in the master branch for the "real" releases?

Not sure if I get that right: Whenever somebody pushes to the `develop` branch, Travis would create a Release on GitHub. And we definitely push more often to the `develop` branch than to the `master` branch. So to reduce the amount of releases, we should only do it for the `master` branch then.

And as I know it from other projects, they also do that only for the master branch (or for a special beta branch if there is one) and not even there for every commit.

**Comment by maxiking203** [comment]
@DManstrator you got it right.
Normally in projects it only get done on the master branch, as I said I only did it for testing in the develop branch. 
But I wanted to get some opinions on how our team members would like it.
Our process manager @pocketinfinity  also recommended that we only do it on the master so I will changed that later.

**Comment by maxiking203** [comment]
The Releases are now only done on master branch.
A updated Travis file is commited to master and develop branch.
There a 3 Releases added to our repo which where for testing issues.
This issue is read for Review. Have a look at the travis build log and the test releases.

**Comment by Kjani01** [comment]
The apk is added to the release and the deploy is displayed in the Travis build log. 
Well done, Maxi!

**Comment by wildeKaiserin** [comment]
Review done, good job!
