### ISSUE TITLE
Thumbnails for BookShelfView

### ISSUE THREAD

**Issue by GiorgioBullo** [mobileappdevhm19/HINT-Reader#44]
I created a new widget to have a nicer and easily automatizable bookshielfview.

**Comment by ghost** [comment]
Saw it, looks amazing!

I'll use your BookCard class for the scrolling BookShelf in issue [33](https://github.com/mobileappdevhm19/HINT-Reader/issues/33)

**Comment by ghost** [comment]
Works wonderfully in the new scrollView, feel free to close the issue.

**Comment by maxiking203** [comment]
Looks good! Better than our old simple bookcovers and we even have a title and author displayed, thats nice!
