### ISSUE TITLE
Play Store Distribution

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#47]
https://flutter.dev/docs/deployment/android

**Comment by maxiking203** [comment]
There is a release prepared in the Google Play Console.
I am not sure it we really should do a full Release (means puplishing the app). So I would leave it as it is for now. On Friday we can ask which typ of a release is wanted.

**Comment by DManstrator** [comment]
@maxiking203 Very nice, thank you!

**Comment by maxiking203** [comment]
Putting the app somehow on the play store was discussed on Friday. 
Seems like there satisfying way for use. 
The apk's and repos are used for alpha testing.

**Comment by maxiking203** [comment]
Since there is a solution I willl try to set it up again

**Comment by maxiking203** [comment]
https://play.google.com/apps/test/RQ-bAgZXPMU/ahAAvZMmgzMnviyAFPU38hHtq-mgHpcbPINjZWDc9GR6i88MH4Xnyacbn4DWzjuI9kF_UyBvM3KJP5-QK2iTRRXmbh

**Comment by maxiking203** [comment]
https://play.google.com/apps/test/RQ-bAgZXPMU/ahAAvZMmjF82C7G34kRuL_-jjxUqWJ3IoELsUbWoFrp0tzNwQsVcNL-KLW5inNODsZNZ05VK2ILFjVa2FWYzDmEch6

**Comment by GiorgioBullo** [comment]
the link above return a 404

**Comment by maxiking203** [comment]
Seems like there are 3 different return for the link 😂
I will have a look at it later again.

**Comment by maxiking203** [comment]
After some testing it seems to depend on the devices

**Comment by maxiking203** [comment]
Please try this link again and give my some feedback:
https://play.google.com/apps/test/RQ-bAgZXPMU/ahAAvZMmjF82C7G34kRuL_-jjxUqWJ3IoELsUbWoFrp0tzNwQsVcNL-KLW5inNODsZNZ05VK2ILFjVa2FWYzDmEch6

Also can you guys find the Hint reader in the Playstore by searching it?

**Comment by wildeKaiserin** [comment]
I can't find the hintreader in the playstore just by searching it. With your link, I also cannot find it (error 404), but on my mobile device, it works

**Comment by GiorgioBullo** [comment]
For me is the same. I have also another problem: in my mobile phone I cannot install it from the link, even if I see the page

**Comment by maxiking203** [comment]
ok the think is...
yesterday I did a full release which means, the hintreader could have been found in the playstore. I think the testing link worked with that. But I dont want the hintreader to be public in the playstore so I took the release back. Maybe thats the reason why link doesnt work.

**Comment by maxiking203** [comment]
@wildeKaiserin I'm also logout from your google Account. So I wont do any changes the next days :D

**Comment by DManstrator** [comment]
From Tobias in the [Moodle Course](https://moodle.hm.edu/mod/forum/discuss.php?d=128123):
>First of all you have to release a Alpha-Testing version on Google Play Console (deadline is **today 28.06**).
>[...]
>At the moment there are no alpha-testing versions published from Team 1, **Team 3**, Team 5 and Team 6. Please contact me if you have done this, so I can include the links to become a tester of your app into the above tutorial.

Do you need help for this, @maxiking203?

**Comment by wildeKaiserin** [comment]
We've already tried it atm but it doesn't work. We're now writing an email to Tobias that last Friday, Mrs. Socher said that we can do Alpha testing via installing the apps from the repos and we then deleted our key. Now it is not possible to upload a new version of our app in the playstore

**Comment by DManstrator** [comment]
I'm at MUAS right now, should I go and have a talk with Tobias? Maybe he can tell me what to do. @wildeKaiserin

**Comment by wildeKaiserin** [comment]
Tobias answered my email. He said, if we talked to Mrs. Socher, then it is okay

**Comment by wildeKaiserin** [comment]
Update: @maxiking203  tried it again and now, it works! Here's the link: 
https://play.google.com/apps/testing/hintreader.hintreader

**Comment by maxiking203** [comment]
https://play.google.com/apps/testing/hintreader.hintreader

I need a gmail Addresse from @DManstrator and @GiorgioBullo to add you to the Test-List in den play Store

**Comment by DManstrator** [comment]
Just wanted to comment the same (just saw the Mail), good job! :D

I don't know if we shouldn't put our mail addresses into the Moodle Course, at least I also cannot test Team 4's App. However I can test Team 2's App but I don't know how they got my Mail Address or how they set it to be open for everyone having only the link, I will open a Issue in their repo and ask for it.

**Comment by maxiking203** [comment]
@DManstrator we cant force you to give us the adress...

Team-2 uses internal-app sharing which is only done with an link and not authentication through email adress

**Comment by wildeKaiserin** [comment]
> Just wanted to comment the same (just saw the Mail), good job! :D
> 
> I don't know if we shouldn't put our mail addresses into the Moodle Course, at least I also cannot test Team 4's App. However I can test Team 2's App but I don't know how they got my Mail Address or how they set it to be open for everyone having only the link, I will open a Issue in their repo and ask for it.

Today, Tobias wrote in moodle, that there is a list where we have to add our gmail addresses, so that google play knows, that we are the testers. so we need your gmail address that you can test the apps

**Comment by DManstrator** [comment]
> @DManstrator we cant force you to give us the adress...
> 
> Team-2 uses internal-app sharing which is only done with an link and not authentication through email adress

I don't have a problem telling you my address, just wanted to point out that there might be a list somewhere. I found a file in Moodle but this only contains @hm addresses so that's not the right one.

Fun Fact: I was able to become a Tester for Team 2 but the link from Google returns 404 for me. :D

(Since this is public here I put my mail address into the Presentation where I'm talking about Code Quality (Slide 10 currently), I hope this is okay for you.)

**Comment by wildeKaiserin** [comment]
The list is in google play console, only a few people can change the list (me included). 
I added you to the list, now you can download the apps from play store with the links in moodle 😄

**Comment by DManstrator** [comment]
Yes, now I can also download the other apps, thank you very much. :)
Pretty smart system I guess. :D

But our app is still [not found](https://play.google.com/store/apps/details?id=hintreader.hintreader&hl=de&ah=o-ow-eeiDr6b6gVHTNV_2d34IGI), I guess we all have to wait for it to be released in the Play Store? Because [Team 4's App](https://play.google.com/store/apps/details?id=edu.hm.cs.mobile.easy_study&hl=de&ah=o-ow-eeiDr6b6gVHTNV_2d34IGI) is already there.

**Comment by wildeKaiserin** [comment]
> But our app is still [not found](https://play.google.com/store/apps/details?id=hintreader.hintreader&hl=de&ah=o-ow-eeiDr6b6gVHTNV_2d34IGI), I guess we all have to wait for it to be released in the Play Store? Because [Team 4's App](https://play.google.com/store/apps/details?id=edu.hm.cs.mobile.easy_study&hl=de&ah=o-ow-eeiDr6b6gVHTNV_2d34IGI) is already there.

normally, it should work... so for me and all others, it works. maybe you can take a look at it later, maybe then this will work for you, too

**Comment by maxiking203** [comment]
> Yes, now I can also download the other apps, thank you very much. :)
> Pretty smart system I guess. :D
> 
> But our app is still [not found](https://play.google.com/store/apps/details?id=hintreader.hintreader&hl=de&ah=o-ow-eeiDr6b6gVHTNV_2d34IGI), I guess we all have to wait for it to be released in the Play Store? Because [Team 4's App](https://play.google.com/store/apps/details?id=edu.hm.cs.mobile.easy_study&hl=de&ah=o-ow-eeiDr6b6gVHTNV_2d34IGI) is already there.

@DManstrator which phone are you using?

**Comment by DManstrator** [comment]
> normally, it should work... so for me and all others, it works. maybe you can take a look at it later, maybe then this will work for you, too

I will, I will also tell you if it worked or still doesn't work.


> @DManstrator which phone are you using?

Samsung Galaxy S5 but I was trying to do that via. a Computer. I can find Team 4's App via. a Computer, but not out App and not Team 2's App.

Just tried it with my smartphone, my phone can find the app in the Play Store but it's not compatible with the version. :D

Android-Version is 6.0.1 if that helps.

**Comment by maxiking203** [comment]
> > normally, it should work... so for me and all others, it works. maybe you can take a look at it later, maybe then this will work for you, too
> 
> I will, I will also tell you if it worked or still doesn't work.
> 
> > @DManstrator which phone are you using?
> 
> Samsung Galaxy S5 but I was trying to do that via. a Computer. I can find Team 4's App via. a Computer, but not out App and not Team 2's App.
> 
> Just tried it with my smartphone, my phone can find the app in the Play Store but it's not compatible with the version. :D
> 
> Android-Version is 6.0.1 if that helps.

I just had a look at the list of phones which are able to run out app. yours is not included 😆

**Comment by DManstrator** [comment]
> I just had a look at the list of phones which are able to run out app. yours is not included

_Hello darkness my old friend.._

**Comment by maxiking203** [comment]
But I am not quit sure what the other groups did that there apps are running on your phone :D
did you try out the apk in our release?

**Comment by DManstrator** [comment]
Installing the APK worked without any problems.. Or wait, last time my phone did not boot correctly anymore after it so I uninstalled the app again. :D

**Comment by maxiking203** [comment]
> Installing the APK worked without any problems.. Or wait, last time my phone did not boot correctly anymore after it so I uninstalled the app again. :D

I guess the play store has an eye one versions and other stuff so it don't allows you to install the app. Which Could be the reason why your phone didn't work after installing the apk manual.

As I heard from @wildeKaiserin and @pocketinfinity that the Link works for the I would say it is more or less a problem with your device and would close this issue.
