### ISSUE TITLE
Web-based backend

### ISSUE THREAD

**Issue by ghost** [mobileappdevhm19/HINT-Reader#48]
## New approach:
Instead of implementing an openGL view for the book page, we will try to call a REST api and get an image from a server.

First course of action: call a sample REST API delivering an image to implement in the front end, so we can change the URL and parameters later, when the backend is realised.

**Comment by ghost** [comment]
e.g.
APOD
https://api.nasa.gov/api.html

**Comment by DManstrator** [comment]
It would help us if the backend could provide the picture directly and not an url to the picture or something similar, else we would have to work around with await / async.

We would then build the needed url with parameters, e. g. `GET /book/{id}/{pageNr}?zoom={-1|0|1}&darkmode={1|0}`, put it basically into `Image.network` and await that the correct picture will be displayed then.

**Comment by ghost** [comment]
This one seems to be on ice for now.

**Comment by wildeKaiserin** [comment]
We now do the alternative with opengl ( #43 )
