### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#49]
We need to set up Firebase Analytics and define what we want to track.

**Comment by maxiking203** [comment]
![image](https://user-images.githubusercontent.com/32635753/60273721-02a19a00-98f7-11e9-8743-9d4c32f1e71d.png)

**Comment by maxiking203** [comment]
![image](https://user-images.githubusercontent.com/32635753/60273756-19e08780-98f7-11e9-8034-b721c244f65c.png)

![image](https://user-images.githubusercontent.com/32635753/60273828-3c72a080-98f7-11e9-8da3-9ba44a6a0b09.png)

**Comment by maxiking203** [comment]
I set up the firebase connection with my google Account. Above scrennshots shoudl show a minimal usage.
I create an special branch for the setup. Because of security concerns I don't really what to merge this fetcher.

Any opinions? @mobileappdevhm19/team-3

**Comment by ghost** [comment]
I appreciate leaving that out of the master branch, creepy analytics are creepy.
Should we decide we need it later, we can always do a pull request.

Thank you for the implementation!

**Comment by Kjani01** [comment]
Well done and thank you for your effort!
although it is kinda creepy, which infos you get, like the GPS.

**Comment by maxiking203** [comment]
@wildeKaiserin as Team lead feel free to close this issue if ist is reasonable for you

**Comment by wildeKaiserin** [comment]
Good job! Thank you for your effort! On monday, I will bring a bag of gummy bears 🥇

**Comment by DManstrator** [comment]
>I appreciate leaving that out of the master branch, creepy analytics are creepy.
>Should we decide we need it later, we can always do a pull request.

@pocketinfinity I thought Firebase Analytics are required? So we have to merge it at some point.
