### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#50]
We already have a github-pages branch, but it's empty so far. We need to set up a documentation of our app in the github-pages. The target group is other students who may want to maintain our app

**Comment by maxiking203** [comment]
Maybe should but the readme of openGL branch also on the github-pages.
Furthermore a short description to every code file we did?

**Comment by GiorgioBullo** [comment]
are we going to do this on monday?

**Comment by wildeKaiserin** [comment]
> are we going to do this on monday?

Good idea!

**Comment by wildeKaiserin** [comment]
The github pages exist now and we're all fine with it 😃
