### ISSUE TITLE
Final presentation

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#51]
https://docs.google.com/presentation/d/1-3pLwbvsahEiN_-kLnAOJijkTdqCgAZd9_FWr1VCuzI/edit?usp=sharing

**Comment by wildeKaiserin** [comment]
so far we have thought about this arrangements:

Introduction & Evolution: @pocketinfinity 
Initial Requirements & Key Learnings: @wildeKaiserin 
Demo: @maxiking203 
Development Process: @Kjani01 

free topics for now:
Architecture
Code Quality

You can assign to a free topic, if you haven't one yet. Please remember: we have about 20min, so everybody should talk for ~3min. If you're not fine with your topic, we'll find a solution.

Please prepare your slide(s) (not too much text!). We will discuss it next Monday, **01.07. at 10AM**

**Comment by Kjani01** [comment]
I'm totally fine with my topic 😄

**Comment by ghost** [comment]
Not too much text is fine (team takahashi method!), and I'll try to keep myself from talking too much.
Maybe we should agree on a hand sign when I start rambling on – like a smack upside the head or something 🤪

**Comment by GiorgioBullo** [comment]
I can speak about the architecture of the app, hoping I'll be able to install the prof. Ruckert project, in this way I can better study it.
Updated list:

Introduction & Evolution: @pocketinfinity 
Initial Requirements & Key Learnings: @wildeKaiserin 
Demo: @maxiking203 
Development Process: @Kjani01 
Architecture: @GiorgioBullo 

free topics for now:
Code Quality

You can assign to a free topic, if you haven't one yet. Please remember: we have about 20min, so everybody should talk for ~3min. If you're not fine with your topic, we'll find a solution.

Please prepare your slide(s) (not too much text!). We will discuss it next Monday, 01.07. at 10AM

**Comment by ghost** [comment]
> hoping I'll be able to install the prof. Ruckert project

There's a readme, I hope it covers all the dependencies.
https://github.com/mobileappdevhm19/HINT-Reader/blob/feature/openGLBook/README.md

**Comment by maxiking203** [comment]
@GiorgioBullo Let me know If I should try to help you get the project running ;)

**Comment by DManstrator** [comment]
I could do the Code Quality Topic but what is this supossed to be? Rating of our Code Quality, working with branches, etc., working with code style / Static Code Analysis, etc.?

I guess last thing, Moodle also didn't tell me more than `Show the code quality and your development process`, would be good to know.

**Comment by Kjani01** [comment]
@DManstrator 
I guess we should show an example of our code and the tests and maybe this graph chart about the different parallel branches we were using 😄 

I will show for our development process (starting with simons chart about our development from the start) the github tools (project board, the issues etc.), I will tell how we worked (meeting regularly, talking via issues, whatsapp, in person)... 

I will do my slides over the weekend, so we could combine mine and yours on monday, because she named the two topics together, but we thought that it would be enough for two of us 😃

**Comment by Kjani01** [comment]
I just made a first draft for my overview of our development process (project board, communication, wiki, etc.). It is the 10. slide in our presentation and you can take a closer look, if you klick on "Abspielen" on the lower right. I have animated the images, so I won't need ten slides 😄 

For the previous slide I would repeat the overview from Simon from the beginning, just as a quick introduction, if that's okay for you.

**Comment by wildeKaiserin** [comment]
> I just made a first draft for my overview of our development process (project board, communication, wiki, etc.). It is the 10. slide in our presentation and you can take a closer look, if you klick on "Abspielen" on the lower right. I have animated the images, so I won't need ten slides 😄
> 
> For the previous slide I would repeat the overview from Simon from the beginning, just as a quick introduction, if that's okay for you.

I really like it! In this way, everybody can see our good teamwork and our effort ;)

**Comment by Kjani01** [comment]
> I really like it! In this way, everybody can see our good teamwork and our effort ;)

Thanks 😃  If anyone comes up with another picture, that describes our development process, just tell me 😀

**Comment by wildeKaiserin** [comment]
> > I really like it! In this way, everybody can see our good teamwork and our effort ;)
> 
> Thanks 😃 If anyone comes up with another picture, that describes our development process, just tell me 😀

I would say if anyone has any idea for any slide, he / she can share it! It's Teamwork 😄

**Comment by maxiking203** [comment]
Nice sildes so far, guys!!
I just added a picture to my demo slide so it doesn't look that empty 😄

**Comment by GiorgioBullo** [comment]
I uploaded my slides about architecture, let me know if we should show any other particular :)

**Comment by Kjani01** [comment]
Great job so far guys!
@wildeKaiserin I would make the font of the _Key Learnings_ a little bigger, if you don't add anything else, but that is critic at the highest stage 😆

**Comment by wildeKaiserin** [comment]
> Great job so far guys!

The plan was to ask you if you all have any ideas what I can add here 😉

**Comment by DManstrator** [comment]
> I guess we should show an example of our code and the tests and maybe this graph chart about the different parallel branches we were using 
> 
> I will do my slides over the weekend, so we could combine mine and yours on monday, because she named the two topics together, but we thought that it would be enough for two of us

Allright, will do that. :+1: 
Maybe I can do some Static Code Analysis just in case, I would use SonarCloud for that, hopefully it supports Dart. ^^

>For the previous slide I would repeat the overview from Simon from the beginning, just as a quick introduction, if that's okay for you.

Sure, great idea!

>I have animated the images, so I won't need ten slides :smile: 

Looks very nice! I moved / changed that Wiki Picture a bit because with all the pictures before it looked a bit confusing.

**Comment by DManstrator** [comment]
For now, I'm done with my part. I will talk more so I don't have much text on my slides. I also worked with stacking images and working with animations so I don't have to do a slide for every picture.

I also went over the slides in general and improved text / layout a bit.

**Comment by ghost** [comment]
Slides 1-12 are mine, feel free to give feedback (aka "simon, please act your age and tone it down with the dank memes!")

**Comment by wildeKaiserin** [comment]
> Slides 1-12 are mine, feel free to give feedback (aka "simon, please act your age and tone it down with the dank memes!")

Wow, you're so creative! I really like it! But the slide with the coffee cups... I think gummy bears would fit better here 😛

**Comment by DManstrator** [comment]
@pocketinfinity I'm loving you for the dank memes. haha

**Comment by Kjani01** [comment]
I just added the green bar at the end of every slide, so the design is consistent

**Comment by wildeKaiserin** [comment]
Ready to present!!! 🎉

**Comment by DManstrator** [comment]
I've added one more slide to the presentation where I'm quickly talking about Static Code Analysis and showing how our project looks like, I hope this is fine for you.

**Comment by wildeKaiserin** [comment]
Looks good in my opinion :)
