### ISSUE TITLE
Idea-Discussion

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#8]
During class last Friday, 12.04.2019, we already discussed possible Ideas. They are displayed in the documen below.

**Comment by ghost** [comment]
[Ideas.pdf](https://github.com/mobileappdevhm19/apps4students-team-3/files/3084289/Ideas.pdf)

**Comment by ghost** [comment]
I'm fine with the TeX Reader (HINT), as long as we're fine with just doing concept explorations for e-reading apps in Flutter if the backend situation (c-bridge?) proves too difficult to manage in the framework.

**Comment by Kjani01** [comment]
The Hint-Reader for academic texts is a nice idea and I think we should try to realize it within flutter.

**Comment by maxiking203** [comment]
I'm fine with Reader too!

**Comment by wildeKaiserin** [comment]
I really like the idea of the Hint-Reader because I know the problem of reading academic texts with the pdf-viewer

**Comment by DManstrator** [comment]
I agree, it seems like it might be the most unique and useful idea out of what we got on the last lecture.

**Comment by maxiking203** [comment]
The Idea-Diskusson is completed. 
We will give the Hintreader a try!
