### ISSUE TITLE
Wiki for Idea-Assignment

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#9]
"Write the Use Cases in the Wiki of your Github repository (under "Our Idea").
Upload all storyboards to the Wiki for your Github Repository."

**Comment by maxiking203** [comment]
Changed the Name of the Wiki-Page to "Use Cases" so it's easier to find them :-)
Some Use Cases are on the Wiki-Page now. More can be added but I think I should be enough for the Assignment.
Storyboards of every Team Member are also on the Wiki Page.
